/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
//import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author melikekecelioglu
 */
public class AddItem extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    String iid;
    String iname;
    String category;
    String serailno;
    String bPrice;
    String sPrice;
    String noofitem;
    Connection con;

    private ImageIcon format = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;
    byte[] nul = null;

    //resizing images to get Height and Width
    public ImageIcon resizeImage(String imagepath, byte[] pic) {
        ImageIcon myImage = null;
        if (imagepath != null) {
            myImage = new ImageIcon(imagepath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblImage.getHeight(), lblImage.getWidth(), Image.SCALE_SMOOTH);

        ImageIcon image = new ImageIcon(img2);

        return image;
    }

    public AddItem() {
        initComponents();
        con = DBConnection.connect();
        autoId();
//        tableLord();
        showTableData();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    //assign the components to variables
    private void getData() {
        iid = txtId.getText();
        iname = txtName.getText();
        category = cmbCategory.getSelectedItem().toString();
        serailno = txtSerialNo.getText();
        bPrice = txtBPrice.getText();
        sPrice = txtSPrice.getText();
        noofitem = txtNoItem.getText();
    }

    //to fill next product's ID, use that method
    private void autoId() {
        try {
            String sql = "SELECT item_id FROM stock ORDER BY item_id DESC LIMIT 1";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("item_id");
                int co = rnno.length();
                //IID (0,1,2)
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                //concat
                String ftxt = txt + snum;
                txtId.setText(ftxt);

            } else {
                txtId.setText("IID1000");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtBPrice = new javax.swing.JTextField();
        txtSPrice = new javax.swing.JTextField();
        txtNoItem = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnl_Add = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl_Delete = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnl_Update = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnl_Clear = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnl_Brows = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddItem = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 255));
        setMaximumSize(new java.awt.Dimension(640, 510));
        setPreferredSize(new java.awt.Dimension(630, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 620, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel1.setText("Item ID");

        jLabel2.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel4.setText("Serial No");

        jLabel5.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel5.setText("B Price");

        jLabel6.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel6.setText("S Price");

        jLabel7.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel7.setText("No of Item");

        cmbCategory.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Computer", "Phone", "Other" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtBPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtSPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtNoItem, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, 351));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 92, 155), 3));
        jPanel4.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 186, 282));

        pnl_Add.setBackground(new java.awt.Color(212, 72, 76));
        pnl_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_AddMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel9.setText("Add");

        javax.swing.GroupLayout pnl_AddLayout = new javax.swing.GroupLayout(pnl_Add);
        pnl_Add.setLayout(pnl_AddLayout);
        pnl_AddLayout.setHorizontalGroup(
            pnl_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AddLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnl_AddLayout.setVerticalGroup(
            pnl_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(pnl_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 20, -1, -1));

        pnl_Delete.setBackground(new java.awt.Color(82, 122, 154));
        pnl_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_DeleteMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel11.setText("Delete");

        javax.swing.GroupLayout pnl_DeleteLayout = new javax.swing.GroupLayout(pnl_Delete);
        pnl_Delete.setLayout(pnl_DeleteLayout);
        pnl_DeleteLayout.setHorizontalGroup(
            pnl_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DeleteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnl_DeleteLayout.setVerticalGroup(
            pnl_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DeleteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(pnl_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 166, -1, -1));

        pnl_Update.setBackground(new java.awt.Color(178, 217, 219));
        pnl_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UpdateMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel10.setText("Update");

        javax.swing.GroupLayout pnl_UpdateLayout = new javax.swing.GroupLayout(pnl_Update);
        pnl_Update.setLayout(pnl_UpdateLayout);
        pnl_UpdateLayout.setHorizontalGroup(
            pnl_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_UpdateLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );
        pnl_UpdateLayout.setVerticalGroup(
            pnl_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_UpdateLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        jPanel4.add(pnl_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 86, -1, -1));

        pnl_Clear.setBackground(new java.awt.Color(229, 229, 229));
        pnl_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ClearMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel12.setText("Clear");

        javax.swing.GroupLayout pnl_ClearLayout = new javax.swing.GroupLayout(pnl_Clear);
        pnl_Clear.setLayout(pnl_ClearLayout);
        pnl_ClearLayout.setHorizontalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClearLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnl_ClearLayout.setVerticalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClearLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(pnl_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 235, -1, -1));

        pnl_Brows.setBackground(new java.awt.Color(174, 133, 141));
        pnl_Brows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_BrowsMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel13.setText("Brows");

        javax.swing.GroupLayout pnl_BrowsLayout = new javax.swing.GroupLayout(pnl_Brows);
        pnl_Brows.setLayout(pnl_BrowsLayout);
        pnl_BrowsLayout.setHorizontalGroup(
            pnl_BrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BrowsLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel13)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pnl_BrowsLayout.setVerticalGroup(
            pnl_BrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BrowsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.add(pnl_Brows, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 294, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 47, 300, 351));

        tblAddItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAddItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAddItem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 404, 620, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_BrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BrowsMouseClicked
        //search for the images
        JFileChooser fchoser = new JFileChooser();
        //open filechooser panel
        fchoser.showOpenDialog(null);
        File f = fchoser.getSelectedFile();
        fname = f.getAbsolutePath();
        ImageIcon micon = new ImageIcon(fname);
        try {
            File image = new File(fname);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            //to store images, set bytes to 1024
            byte[] buf = new byte[1024];
            for (int readnum; (readnum = fis.read(buf)) != -1;) {
                baos.write(buf, 0, readnum);
            }
            pimage = baos.toByteArray();
            lblImage.setIcon(resizeImage(fname, buf));
        } catch (Exception ex) {
//            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);

        }


    }//GEN-LAST:event_pnl_BrowsMouseClicked

    private void pnl_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_AddMouseClicked
        getData();
        //insert datas to database
        try {
            String q = "INSERT INTO  `stock` (\n"
                    + "  `item_id` ,\n"
                    + "  `item_name` ,\n"
                    + "  `category` ,\n"
                    + "  `serial_no` ,\n"
                    + "  `buy_price` ,\n"
                    + "  `saie_price` ,\n"
                    + "  `no_of_items` ,\n"
                    + "  `image`,\n"
                    + "  `mark` ) VALUES (?,?,?,?,?,?,?,?,?)";

            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setString(1, iid);
            pst.setString(2, iname);
            pst.setString(3, category);
            pst.setString(4, serailno);
            pst.setString(5, bPrice);
            pst.setString(6, sPrice);
            pst.setString(7, noofitem);
            pst.setBytes(8, pimage);
            pst.setString(9, "1");
            pst.execute();
            //clear txtfiles 
            clearData();
            // tableLord();
            showTableData();
        } catch (Exception ex) {
            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_pnl_AddMouseClicked

    private void pnl_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UpdateMouseClicked
        getData();
//        try {
//
//            String squpdate = "UPDATE  `stock` SET (\n"
//                    + "  `item_name`=? ,\n"
//                    + "  `category`=? ,\n"
//                    + "  `serial_no`=? ,\n"
//                    + "  `buy_price`=? ,\n"
//                    + "  `saie_price`=? ,\n"
//                    + "  `no_of_items`=? ,\n"
//                    + "  `image`,\n"
//                    + "WHERE item_id" + iid + "'";
//            pst = (PreparedStatement) con.prepareStatement(squpdate);
//
//            pst.setString(1, iname);
//            pst.setString(2, category);
//            pst.setString(3, serailno);
//            pst.setString(4, bPrice);
//            pst.setString(5, sPrice);
//            // pst.setString(6, "hello");
////            pst.setBytes(7, nul);
//            pst.setString(6, noofitem);
//            pst.setBytes(7, pimage);
//            pst.executeUpdate();
//        } catch (Exception ex) {
//            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
//        }

        //////
        //update database item indormations
        try {
            String sql = "UPDATE stock SET item_name=?, category=?, serial_no=?, buy_price=?, saie_price=?, no_of_items=?, image=? WHERE item_id=?";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, iname);
            pst.setString(2, category);
            pst.setString(3, serailno);
            pst.setString(4, bPrice);
            pst.setString(5, sPrice);
            pst.setString(6, noofitem);
            pst.setBytes(7, pimage);
            pst.setString(8, iid);
            pst.execute();
            JOptionPane.showMessageDialog(null, "updated succesfully");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        clearData();
        //   tableLord();
        showTableData();
    }//GEN-LAST:event_pnl_UpdateMouseClicked

    private void pnl_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ClearMouseClicked
        clearData();
    }//GEN-LAST:event_pnl_ClearMouseClicked

    private void pnl_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_DeleteMouseClicked
//        try {
//            String sql = "DELETE FROM 'stock' WHERE item_id='" + iid + "'";
//            pst = con.prepareStatement(sql);
//            pst.execute();
//            //tableLord();
//            showTableData();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }

        /*try {
            String sql = "DELETE FROM stock WHERE item_id =?";
            pst = con.prepareStatement(sql);
            pst.setString(1, RollNo.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "deleted succesfully");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        showTableData();*/
//        
//        try {
//            String sql = "DELETE stock SET item_name=?, category=?, serial_no=?, buy_price=?, saie_price=?, no_of_items=?, image=? WHERE item_id=?";
//            pst = (PreparedStatement) con.prepareStatement(sql);
//
//            pst.setString(1, iname);
//            pst.setString(2, category);
//            pst.setString(3, serailno);
//            pst.setString(4, bPrice);
//            pst.setString(5, sPrice);
//            pst.setString(6, noofitem);
//            pst.setBytes(7, pimage);
//            pst.setString(8, iid);
//            clearData(); 
//            pst.execute();
//
//            JOptionPane.showMessageDialog(null, "DELETED succesfully");
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }
//        showTableData();
        ///
////        try {
////            String sql = "DELETE stock WHERE item_id =?";
////            pst = con.prepareStatement(sql);
////            pst.setString(1, iid);
////            pst.execute();
////            JOptionPane.showMessageDialog(null, "deleted succesfully");
////
////            String str = "N/A";
////            try {
////                int val = Integer.parseInt(str);
////            } catch (NumberFormatException e) {
////                JOptionPane.showMessageDialog(rootPane, "NOT A NUMBER");
////            }
////            showTableData();
////            clearData();
////        } catch (Exception ex) {
////            JOptionPane.showMessageDialog(null, ex);
////        }
////        showTableData();



        //delete from database
        int row = tblAddItem.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblAddItem.getModel();

        String selected = model.getValueAt(row, 0).toString();

        if (row >= 0) {

            model.removeRow(row);

            try {
                String sql = "delete from stock where item_id= ?";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, selected);
                stmt.executeUpdate();
            } catch (Exception w) {
                JOptionPane.showMessageDialog(this, "Connection Error!");
            }
        }


    }//GEN-LAST:event_pnl_DeleteMouseClicked

    private void tblAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAddItemMouseClicked
            
        
        //add item to database
        String id;
        DefaultTableModel tmodel = (DefaultTableModel) tblAddItem.getModel();
        int selectrowindex = tblAddItem.getSelectedRow();
        id = (tmodel.getValueAt(selectrowindex, 0).toString());

        try {
            String sql = "SELECT 'item_id', 'item_name', 'category', 'serial_no', 'buy_price', 'saie_price','no_of_items', 'image', 'mark' FROM stock WHERE item_id='" + id + "'";
            String sql1 = "SELECT * FROM stock where item_id ='" + id + "'";
            pst = (PreparedStatement) con.prepareStatement(sql1);
            rs = pst.executeQuery();

            if (rs.next()) {
//
//                String setid = rs.getString("item_id");
//                txtId.setText(setid);
//                String setname = rs.getString("item_name");
//                txtName.setText(setname);

                txtId.setText(rs.getString("item_id"));
                txtName.setText(rs.getString("item_name"));
                cmbCategory.setSelectedItem(rs.getString("category"));
                txtSerialNo.setText(rs.getString("serial_no"));
                txtBPrice.setText(rs.getString("buy_price"));
                txtSPrice.setText(rs.getString("saie_price"));
                txtNoItem.setText(rs.getString("no_of_items"));
                byte[] imageData = rs.getBytes("image");
                format = new ImageIcon(imageData);
                Image mm = format.getImage();
                Image img2 = mm.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(img2);
                lblImage.setIcon(image);
            } else {
                System.out.println("YOU ARE ON THE ELSE PART");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }


    }//GEN-LAST:event_tblAddItemMouseClicked

    //method to select datas to table synchronised
    private void tableLord() {
        try {
            String sql = "SELECT 'item_id', 'item_name', 'category', 'serial_no', 'buy_price', 'saie_price','no_of_items', 'image', 'mark' FROM 'stock'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblAddItem.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {

        }
    }
    //show datas on table
    public void showTableData() {
        try {
            String sql = "SELECT * FROM stock";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblAddItem.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //null every component
    private void clearData() {
        autoId();
        txtName.setText("");
        cmbCategory.setSelectedIndex(0);
        txtSerialNo.setText("");
        txtBPrice.setText("");
        txtSPrice.setText("");
        txtNoItem.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel pnl_Add;
    private javax.swing.JPanel pnl_Brows;
    private javax.swing.JPanel pnl_Clear;
    private javax.swing.JPanel pnl_Delete;
    private javax.swing.JPanel pnl_Update;
    private javax.swing.JTable tblAddItem;
    private javax.swing.JTextField txtBPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoItem;
    private javax.swing.JTextField txtSPrice;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
