/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author melikekecelioglu
 */
public class ColorFun extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    //create an object from Calendar 
    Calendar calendar;
    //SimpleDateFormat objects to take the time day and date
    SimpleDateFormat timeFormat;
    SimpleDateFormat dayFormat;
    SimpleDateFormat dateFormat;
    //string variables for every kind of 'time'
    String time;
    String day;
    String date;

    public ColorFun() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtn_preview = new javax.swing.JRadioButton();
        rbtn_select = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panelColor = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelColor1 = new javax.swing.JPanel();
        slider_red = new javax.swing.JSlider();
        slider_green = new javax.swing.JSlider();
        slider_blue = new javax.swing.JSlider();
        colorPanel = new javax.swing.JPanel();
        spinner_red = new javax.swing.JSpinner();
        spinner_green = new javax.swing.JSpinner();
        spinner_Blue = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 45, -1, -1));

        buttonGroup1.add(rbtn_preview);
        rbtn_preview.setText("Preview");
        rbtn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_previewActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        buttonGroup1.add(rbtn_select);
        rbtn_select.setText("Select Color");
        rbtn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_selectActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Select Color", jPanel2);

        slider_red.setBackground(new java.awt.Color(204, 0, 51));
        slider_red.setForeground(new java.awt.Color(255, 255, 255));
        slider_red.setMaximum(255);
        slider_red.setMinimum(15);
        slider_red.setPaintLabels(true);
        slider_red.setPaintTicks(true);
        slider_red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_redStateChanged(evt);
            }
        });
        slider_red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slider_redMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slider_redMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slider_redMouseReleased(evt);
            }
        });

        slider_green.setBackground(new java.awt.Color(51, 255, 51));
        slider_green.setForeground(new java.awt.Color(255, 255, 255));
        slider_green.setMaximum(255);
        slider_green.setMinimum(15);
        slider_green.setPaintLabels(true);
        slider_green.setPaintTicks(true);
        slider_green.setToolTipText("");
        slider_green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_greenStateChanged(evt);
            }
        });

        slider_blue.setBackground(new java.awt.Color(0, 0, 204));
        slider_blue.setForeground(new java.awt.Color(255, 255, 255));
        slider_blue.setMaximum(255);
        slider_blue.setMinimum(15);
        slider_blue.setPaintLabels(true);
        slider_blue.setPaintTicks(true);
        slider_blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_blueStateChanged(evt);
            }
        });

        colorPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        spinner_red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_redStateChanged(evt);
            }
        });

        spinner_green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_greenStateChanged(evt);
            }
        });

        spinner_Blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_BlueStateChanged(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "R", " ", "G", " ", "B" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout panelColor1Layout = new javax.swing.GroupLayout(panelColor1);
        panelColor1.setLayout(panelColor1Layout);
        panelColor1Layout.setHorizontalGroup(
            panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spinner_Blue, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addComponent(spinner_green, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(spinner_red, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelColor1Layout.setVerticalGroup(
            panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColor1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(panelColor1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColor1Layout.createSequentialGroup()
                        .addComponent(slider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelColor1Layout.createSequentialGroup()
                            .addComponent(spinner_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(spinner_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(spinner_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Slide for the R , G, B Values", panelColor1);

        jTabbedPane1.addTab("Make Your Own Color!", jTabbedPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_previewActionPerformed
        //to change the color of panel we need to use Window object
        Window parentWindow = SwingUtilities.windowForComponent(rbtn_preview);
        //to see synchronised color changes, use changelistener 
        //set the color for panel to see it 
        JColorChooser jcc = new JColorChooser();
        jcc.getSelectionModel().addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                panelColor.setBackground(jcc.getColor());
            }
        });
        //JDialog to control represents a top level window 
        JDialog dialog = new JDialog(parentWindow);
        dialog.add(jcc);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_rbtn_previewActionPerformed

    private void rbtn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_selectActionPerformed
        JColorChooser jcc = new JColorChooser();
        Color c = jcc.showDialog(null, "please select a color", Color.red);
        panelColor.setBackground(c);

    }//GEN-LAST:event_rbtn_selectActionPerformed

    private void slider_redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_redStateChanged

        colorChoose();
        jList1.setSelectedIndex(0);
    }//GEN-LAST:event_slider_redStateChanged

    private void slider_redMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_redMouseClicked


    }//GEN-LAST:event_slider_redMouseClicked

    private void slider_redMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_redMousePressed

    }//GEN-LAST:event_slider_redMousePressed

    private void slider_redMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_redMouseReleased

    }//GEN-LAST:event_slider_redMouseReleased

    private void slider_greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_greenStateChanged
        colorChoose();
         jList1.setSelectedIndex(2);
    }//GEN-LAST:event_slider_greenStateChanged

    private void slider_blueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_blueStateChanged
        colorChoose();
         jList1.setSelectedIndex(4);
    }//GEN-LAST:event_slider_blueStateChanged

    private void spinner_redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_redStateChanged
        //get values and set from spinner to slider
        int value2 = (int) spinner_red.getValue();
        slider_red.setValue(value2);
    }//GEN-LAST:event_spinner_redStateChanged

    private void spinner_greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_greenStateChanged
        //get values and set from spinner to slider
        int value2 = (int) spinner_green.getValue();
        slider_green.setValue(value2);
    }//GEN-LAST:event_spinner_greenStateChanged

    private void spinner_BlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_BlueStateChanged
        //get values and set from spinner to slider
        int value2 = (int) spinner_Blue.getValue();
        slider_blue.setValue(value2);
    }//GEN-LAST:event_spinner_BlueStateChanged

    //methos to assign and use  R G B values
    private void colorChoose() {
        int R, G, B;
        R = slider_red.getValue();
        G = slider_green.getValue();
        B = slider_blue.getValue();
        colorPanel.setBackground(new Color(R, G, B));
        spinner_Blue.setValue(slider_blue.getValue());
        spinner_green.setValue(slider_green.getValue());
        spinner_red.setValue(slider_red.getValue());
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorFun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelColor1;
    private javax.swing.JRadioButton rbtn_preview;
    private javax.swing.JRadioButton rbtn_select;
    private javax.swing.JSlider slider_blue;
    private javax.swing.JSlider slider_green;
    private javax.swing.JSlider slider_red;
    private javax.swing.JSpinner spinner_Blue;
    private javax.swing.JSpinner spinner_green;
    private javax.swing.JSpinner spinner_red;
    // End of variables declaration//GEN-END:variables
}
