/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import keeptoo.Drag;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 * @file melike_kecelioglu_1921221014_bp2_project
 * @description inventroy system
 * @assignement final project
 * @date 05/06/2021
 * @author Melike KECELIOGLU / melike.kecelioglu@stu.fsm.edu.tr
 */
/**
 *
 * @author melikekecelioglu
 */
public class LogIn_1 extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;

    int x, y;

    public LogIn_1() {
        initComponents();
        this.setLocationRelativeTo(this);
        con = DBConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_Username = new javax.swing.JTextField();
        pssField = new javax.swing.JPasswordField();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kbtn_SignIn = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        kbtn_SignUp = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_ForgotPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(40);
        kGradientPanel1.setkEndColor(new java.awt.Color(70, 90, 117));
        kGradientPanel1.setkGradientFocus(350);
        kGradientPanel1.setkStartColor(new java.awt.Color(17, 50, 71));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Username.setBackground(new Color(0,0,0,0));
        txt_Username.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setToolTipText("");
        txt_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 380, 30));

        pssField.setBackground(new Color(0,0,0,0));
        pssField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        pssField.setForeground(new java.awt.Color(255, 255, 255));
        pssField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(pssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 380, -1));

        btn_exit.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("   X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 50, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        kbtn_SignIn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0)));
        kbtn_SignIn.setForeground(new java.awt.Color(0, 0, 0));
        kbtn_SignIn.setText("SignIn");
        kbtn_SignIn.setToolTipText("");
        kbtn_SignIn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        kbtn_SignIn.setkBackGroundColor(new Color(0,0,0,0));
        kbtn_SignIn.setkBorderRadius(40);
        kbtn_SignIn.setkEndColor(new java.awt.Color(239, 241, 223));
        kbtn_SignIn.setkHoverEndColor(new java.awt.Color(239, 241, 223));
        kbtn_SignIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtn_SignIn.setkHoverStartColor(new java.awt.Color(81, 128, 161));
        kbtn_SignIn.setkIndicatorThickness(5);
        kbtn_SignIn.setkSelectedColor(new java.awt.Color(255, 204, 204));
        kbtn_SignIn.setkStartColor(new Color(0,0,0,0));
        kbtn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn_SignInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kbtn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 120, 40));

        jLabel3.setText("or");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        kbtn_SignUp.setText("SignUp");
        kbtn_SignUp.setkBorderRadius(40);
        kbtn_SignUp.setkEndColor(new java.awt.Color(255, 204, 204));
        kbtn_SignUp.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kbtn_SignUp.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtn_SignUp.setkHoverStartColor(new java.awt.Color(81, 128, 161));
        kbtn_SignUp.setkSelectedColor(new java.awt.Color(255, 204, 204));
        kbtn_SignUp.setkStartColor(new Color(0,0,0,0));
        kbtn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn_SignUpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kbtn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 110, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lbl_ForgotPass.setText("Forgot Password?");
        lbl_ForgotPass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_ForgotPassMouseMoved(evt);
            }
        });
        lbl_ForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ForgotPassMousePressed(evt);
            }
        });
        kGradientPanel1.add(lbl_ForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -7, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed

    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        //set loaction of frame
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void kbtn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn_SignInActionPerformed
        //warnings in case of empty string
        String userName = "";
        String pass = "";
        userName = txt_Username.getText();
        pass = pssField.getText();
        if (userName.equals("") && pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter username and password");
        } else if ((!userName.equals("")) && pass.equals("")) {

            JOptionPane.showMessageDialog(this, "Password required");
        } else if (userName.equals("") && (!pass.equals(""))) {
            JOptionPane.showMessageDialog(this, "Please enter username");
        }

        String password;
        String pword = pssField.getText();
        //check the database for username, password
        try {
            String sql1 = "SELECT password FROM register WHERE user_name ='" + txt_Username.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql1);
            rs = pst.executeQuery();

            if (rs.next()) {
                password = (rs.getString("password"));
                if (password.equals(pword)) {
                    Home ho = new Home();
                    ho.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password incorrect");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "there is a problem");
        }


    }//GEN-LAST:event_kbtn_SignInActionPerformed

    private void lbl_ForgotPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ForgotPassMousePressed
       
        SendCode1 sc = new SendCode1();
        this.setVisible(true);
        sc.setVisible(true);

    }//GEN-LAST:event_lbl_ForgotPassMousePressed

    private void lbl_ForgotPassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ForgotPassMouseMoved
       //set cursor the hand cursor type.
        lbl_ForgotPass.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbl_ForgotPassMouseMoved

    private void kbtn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn_SignUpActionPerformed
        SignUp1 sg = new SignUp1();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kbtn_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton kbtn_SignIn;
    private keeptoo.KButton kbtn_SignUp;
    private javax.swing.JLabel lbl_ForgotPass;
    private javax.swing.JPasswordField pssField;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
