/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author melikekecelioglu
 */
public class Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;

    public Report() {
        initComponents();
        con = DBConnection.connect();
        saleLord();
        //showTableData();
        stockLord();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    //select datas from database, set model and put datas into jtables
    private void saleLord() {
        try {
            String sql = "SELECT  'sale_id', 'item_name', 'unit_price', 'no_of_item', 'total_price', 'discount', 'payable', 'cash', 'balance', 'date' FROM 'sale'";
            String sql1 = "SELECT * FROM sale";
            pst = (PreparedStatement) con.prepareStatement(sql1);
            rs = pst.executeQuery();
            tbl_Sale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {

        }
    }

    //select datas from database, set model and put datas into jtables
    public void showTableData() {
        try {
            String sql = "SELECT * FROM stock";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tbl_Stock.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
         
        }
    }

    //select datas from database, set model and put datas into jtables
    private void stockLord() {
        try {
            String sql = "SELECT  'sale_id', 'item_name', 'unit_price', 'no_of_item', 'total_price', 'discount','payable', 'cash', 'balance','date' FROM 'stock'";
            String sql1 = "SELECT * FROM stock";
            pst = (PreparedStatement) con.prepareStatement(sql1);
            rs = pst.executeQuery();
            tbl_Stock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnl_Process = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnl_Clear = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Sale = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fDate = new com.toedter.calendar.JDateChooser();
        tDate = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        pnl_Print2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnl_Clear2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Stock = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_Category = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 51, 255));
        setMaximumSize(new java.awt.Dimension(640, 510));
        setPreferredSize(new java.awt.Dimension(630, 510));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        pnl_Process.setBackground(new java.awt.Color(155, 201, 227));
        pnl_Process.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ProcessMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel11.setText("Process");

        javax.swing.GroupLayout pnl_ProcessLayout = new javax.swing.GroupLayout(pnl_Process);
        pnl_Process.setLayout(pnl_ProcessLayout);
        pnl_ProcessLayout.setHorizontalGroup(
            pnl_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ProcessLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnl_ProcessLayout.setVerticalGroup(
            pnl_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Clear.setBackground(new java.awt.Color(75, 156, 185));
        pnl_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ClearMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel10.setText("Clear");

        javax.swing.GroupLayout pnl_ClearLayout = new javax.swing.GroupLayout(pnl_Clear);
        pnl_Clear.setLayout(pnl_ClearLayout);
        pnl_ClearLayout.setHorizontalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnl_ClearLayout.setVerticalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ClearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        tbl_Sale.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 12)); // NOI18N
        tbl_Sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Sale);

        jLabel14.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel14.setText("Sales");

        jLabel15.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel15.setText("From");

        jLabel16.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel16.setText("To");

        fDate.setDateFormatString("yyyy-MM-dd");

        tDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_Process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(fDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnl_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnl_Process, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        pnl_Print2.setBackground(new java.awt.Color(85, 158, 163));

        jLabel17.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel17.setText("Print");

        javax.swing.GroupLayout pnl_Print2Layout = new javax.swing.GroupLayout(pnl_Print2);
        pnl_Print2.setLayout(pnl_Print2Layout);
        pnl_Print2Layout.setHorizontalGroup(
            pnl_Print2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Print2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnl_Print2Layout.setVerticalGroup(
            pnl_Print2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Print2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_Clear2.setBackground(new java.awt.Color(109, 180, 139));
        pnl_Clear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_Clear2MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel19.setText("Clear");

        javax.swing.GroupLayout pnl_Clear2Layout = new javax.swing.GroupLayout(pnl_Clear2);
        pnl_Clear2.setLayout(pnl_Clear2Layout);
        pnl_Clear2Layout.setHorizontalGroup(
            pnl_Clear2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Clear2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnl_Clear2Layout.setVerticalGroup(
            pnl_Clear2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Clear2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(14, 14, 14))
        );

        tbl_Stock.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 12)); // NOI18N
        tbl_Stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_Stock);

        jLabel20.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel20.setText("Stock");

        jLabel21.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel21.setText("Category");

        txt_Category.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CategoryKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_Print2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_Clear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnl_Print2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_ProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ProcessMouseClicked
        //get dates from component into a string
        String saleFDate = ((JTextField) fDate.getDateEditor().getUiComponent()).getText();
        String saleTDate = ((JTextField) tDate.getDateEditor().getUiComponent()).getText();
        saleLord();
        //if fdate is bigger than0  and tdate is empty brackets will come over here
        if (saleFDate.length() > 0 && saleTDate.isEmpty()) {
            try {

                String sql = "SELECT  'sale_id', 'item_name', 'unit_price', 'no_of_item', 'total_price', 'discount','payable', 'cash', 'balance','date' FROM 'sale'";
                String sql1 = "SELECT * FROM sale WHERE date='" + saleFDate + "'";
                pst = (PreparedStatement) con.prepareStatement(sql1);
                rs = pst.executeQuery();
                tbl_Sale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch (Exception ex) {

            }
        }
        //if fdate is bigger than 0 tdate is bigger than 0 brackets will come over here
        else if (saleFDate.length() > 0 && saleTDate.length() > 0) {
            try {

                String sql = "SELECT  'sale_id', 'item_name', 'unit_price', 'no_of_item', 'total_price', 'discount','payable', 'cash', 'balance','date' FROM 'sale'";
                String sql1 = "SELECT * FROM sale WHERE date BETWEEN '" + saleFDate + "' AND '" + saleTDate + "'";
                pst = (PreparedStatement) con.prepareStatement(sql1);
                rs = pst.executeQuery();
                tbl_Sale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch (Exception ex) {

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Select Date");
        }

    }//GEN-LAST:event_pnl_ProcessMouseClicked

    private void txt_CategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CategoryKeyReleased
       
        // search categories synchronised with key releasing
        String category = txt_Category.getText();
        if (txt_Category.getText().length() > 0) {

            try {
                String sql = "SELECT  'sale_id', 'item_name', 'unit_price', 'no_of_item', 'total_price', 'discount','payable', 'cash', 'balance','date' FROM 'stock'";
                String sql1 = "SELECT * FROM stock WHERE category LIKE '%" + category + "%'";
                pst = (PreparedStatement) con.prepareStatement(sql1);
                rs = pst.executeQuery();
                tbl_Stock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        } else {
            stockLord();
        }
    }//GEN-LAST:event_txt_CategoryKeyReleased

    private void pnl_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ClearMouseClicked
        
        //clear textfields
        ((JTextField) fDate.getDateEditor().getUiComponent()).setText("");
        ((JTextField) tDate.getDateEditor().getUiComponent()).setText("");
        saleLord();
    }//GEN-LAST:event_pnl_ClearMouseClicked

    private void pnl_Clear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Clear2MouseClicked
        txt_Category.setText("");
        stockLord();
    }//GEN-LAST:event_pnl_Clear2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_Clear;
    private javax.swing.JPanel pnl_Clear2;
    private javax.swing.JPanel pnl_Print2;
    private javax.swing.JPanel pnl_Process;
    private com.toedter.calendar.JDateChooser tDate;
    private javax.swing.JTable tbl_Sale;
    private javax.swing.JTable tbl_Stock;
    private javax.swing.JTextField txt_Category;
    // End of variables declaration//GEN-END:variables
}
