/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import javax.swing.JOptionPane;
import keeptoo.Drag;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author melikekecelioglu
 */
public class Reset1 extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;

    int x, y;
    public String user;

    public Reset1(String username) {
        this.user = username;
        initComponents();
        this.setLocationRelativeTo(this);
        this.setAlwaysOnTop(true);
        con = DBConnection.connect();

    }

    public Reset1() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setAlwaysOnTop(true);
        con = DBConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_Email = new javax.swing.JTextField();
        txt_VerifyPass = new javax.swing.JPasswordField();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_LogIn = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        txt_NewPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_e = new javax.swing.JLabel();
        lbl_signUpRePassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(40);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 255, 255));
        kGradientPanel1.setkGradientFocus(350);
        kGradientPanel1.setkStartColor(new java.awt.Color(70, 90, 117));
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Email.setBackground(new Color(0,0,0,0));
        txt_Email.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));
        txt_Email.setToolTipText("");
        txt_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_EmailKeyReleased(evt);
            }
        });
        kGradientPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 320, 30));

        txt_VerifyPass.setBackground(new Color(0,0,0,0));
        txt_VerifyPass.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_VerifyPass.setForeground(new java.awt.Color(255, 255, 255));
        txt_VerifyPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_VerifyPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VerifyPassActionPerformed(evt);
            }
        });
        txt_VerifyPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_VerifyPassKeyReleased(evt);
            }
        });
        kGradientPanel1.add(txt_VerifyPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 320, 30));

        btn_exit.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("   X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setText("Verify Password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        btn_LogIn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0)));
        btn_LogIn.setForeground(new java.awt.Color(0, 0, 0));
        btn_LogIn.setText("Update");
        btn_LogIn.setToolTipText("");
        btn_LogIn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_LogIn.setkBackGroundColor(new Color(0,0,0,0));
        btn_LogIn.setkBorderRadius(40);
        btn_LogIn.setkEndColor(new java.awt.Color(153, 153, 153));
        btn_LogIn.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        btn_LogIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_LogIn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btn_LogIn.setkIndicatorThickness(5);
        btn_LogIn.setkPressedColor(new Color(0,0,0,0));
        btn_LogIn.setkSelectedColor(new Color(0,0,0,0));
        btn_LogIn.setkStartColor(new Color(0,0,0,0));
        btn_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 120, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txt_NewPassword.setBackground(new Color(0,0,0,0));
        txt_NewPassword.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_NewPassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_NewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 320, 30));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel5.setText("New Password");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txt_Username.setBackground(new Color(0,0,0,0));
        txt_Username.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setToolTipText("");
        txt_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 30));

        txt_ID.setBackground(new Color(0,0,0,0));
        txt_ID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_ID.setToolTipText("");
        txt_ID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 320, 30));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setText("Username");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel7.setText("E-mail");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        kGradientPanel1.add(lbl_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 320, 20));
        kGradientPanel1.add(lbl_signUpRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 320, 20));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 450, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed


    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogInActionPerformed
        //set components to variables
        String uname = txt_Username.getText();
        String email = txt_Email.getText();
        String pword = txt_NewPassword.getText();
        String rpword = txt_VerifyPass.getText();

        //update the register database
        try {
            String sql = "UPDATE register SET user_name=?, email=?, password=?, re_password=? WHERE id= '" + txt_ID.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, uname);
            pst.setString(2, email);
            pst.setString(3, pword);
            pst.setString(4, rpword);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Updated Succesfully");
            LogIn_1 lo = new LogIn_1();
            lo.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);

        }


    }//GEN-LAST:event_btn_LogInActionPerformed

    private void txt_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailKeyReleased

        //use regex, pattern and matcher to control e-mail
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][com]{3,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txt_Email.getText());
        if (!match.matches()) {
            lbl_e.setText("Email is incorrect");
        } else {
            lbl_e.setText(null);
        }
    }//GEN-LAST:event_txt_EmailKeyReleased

    private void txt_VerifyPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_VerifyPassKeyReleased

        // control if passwords matches
        if (txt_VerifyPass.getText().isEmpty()) {
            lbl_signUpRePassword.setText("Password must not be empty");
            lbl_signUpRePassword.setVisible(true);
            return;
        } else {
            if (txt_VerifyPass.getText().compareTo(txt_NewPassword.getText()) != 0) {
                lbl_signUpRePassword.setText("RePassword must match with password");
                lbl_signUpRePassword.setVisible(true);
                return;
            } else {
                lbl_signUpRePassword.setVisible(false);
            }
        }
    }//GEN-LAST:event_txt_VerifyPassKeyReleased

    private void txt_VerifyPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VerifyPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_VerifyPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset1().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_LogIn;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_e;
    private javax.swing.JLabel lbl_signUpRePassword;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JPasswordField txt_NewPassword;
    private javax.swing.JTextField txt_Username;
    private javax.swing.JPasswordField txt_VerifyPass;
    // End of variables declaration//GEN-END:variables
}
