/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.print.*;
import javax.print.*;
import javax.print.attribute.*;
import javax.print.attribute.standard.*;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author melikekecelioglu
 */
public class Sale extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;
    private ImageIcon format = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;

    String sid;
    String iid;
    String uprice;
    String noofitem;
    String totalprice;
    String discount;
    String payble;
    String cash;
    String balance;
    String date;

    public Sale() {
        initComponents();
        con = DBConnection.connect();
        billHeader();
        autoId();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    //get all datas into string variables, 
    //use a method for it to not to write everytime
    private void lordData() {
        sid = lblSid.getText();
        iid = txt_ItemId.getText();
        uprice = txt_UPrice.getText();
        noofitem = txt_NoItem.getText();
        totalprice = txt_TPrice.getText();
        discount = txt_Discount.getText();
        payble = txt_Payble.getText();
        cash = txt_Cash.getText();
        balance = txt_Balance.getText();
        LocalDate ndate = LocalDate.now();
        date = ndate + "";

    }

    //method to get datas on stock and sets the table inside
    private void itemLord() {
        try {
            String sql = "SELECT 'item_name', 'serial_no', 'saie_price', 'image' FROM stock WHERE item_id='" + txt_ItemId.getText() + "'";
            String sql1 = "SELECT * FROM stock where item_id = '" + txt_ItemId.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql1);
            rs = pst.executeQuery();

            if (rs.next()) {
                txt_ItemName.setText(rs.getString("item_name"));

                txt_SerialNo.setText(rs.getString("serial_no"));

                txt_UPrice.setText(rs.getString("saie_price"));

                byte[] imageData = rs.getBytes("image");
                format = new ImageIcon(imageData);
                Image mm = format.getImage();
                Image img2 = mm.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(img2);
                lblImage.setIcon(image);
            } else {

            }

        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ItemId = new javax.swing.JTextField();
        txt_ItemName = new javax.swing.JTextField();
        txt_SerialNo = new javax.swing.JTextField();
        txt_UPrice = new javax.swing.JTextField();
        txt_NoItem = new javax.swing.JTextField();
        txt_TPrice = new javax.swing.JTextField();
        txt_Discount = new javax.swing.JTextField();
        txt_Payble = new javax.swing.JTextField();
        txt_Cash = new javax.swing.JTextField();
        txt_Balance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnl_Sales = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl_Print = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnl_Clear = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Bill = new javax.swing.JTextArea();
        lblSid = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 255));
        setMaximumSize(new java.awt.Dimension(640, 510));
        setPreferredSize(new java.awt.Dimension(630, 510));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel1.setText("Item ID");

        jLabel2.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel3.setText("Serial No");

        jLabel4.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel4.setText("Unit Price");

        jLabel5.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel5.setText("No of Item");

        jLabel6.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel6.setText("Total Price");

        jLabel7.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel7.setText("Discount");

        txt_ItemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ItemIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ItemIdKeyTyped(evt);
            }
        });

        txt_UPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UPriceActionPerformed(evt);
            }
        });

        txt_NoItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NoItemKeyReleased(evt);
            }
        });

        txt_TPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TPriceActionPerformed(evt);
            }
        });

        txt_Discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DiscountKeyReleased(evt);
            }
        });

        txt_Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CashKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel14.setText("Payble");

        jLabel15.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel15.setText("Cash");

        jLabel16.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel16.setText("Balance");

        pnl_Sales.setBackground(new java.awt.Color(237, 79, 90));
        pnl_Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_SalesMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel9.setText("Sales");

        javax.swing.GroupLayout pnl_SalesLayout = new javax.swing.GroupLayout(pnl_Sales);
        pnl_Sales.setLayout(pnl_SalesLayout);
        pnl_SalesLayout.setHorizontalGroup(
            pnl_SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SalesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnl_SalesLayout.setVerticalGroup(
            pnl_SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_Print.setBackground(new java.awt.Color(156, 212, 211));
        pnl_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_PrintMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel10.setText("Print");

        javax.swing.GroupLayout pnl_PrintLayout = new javax.swing.GroupLayout(pnl_Print);
        pnl_Print.setLayout(pnl_PrintLayout);
        pnl_PrintLayout.setHorizontalGroup(
            pnl_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PrintLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_PrintLayout.setVerticalGroup(
            pnl_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PrintLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pnl_Clear.setBackground(new java.awt.Color(102, 165, 223));
        pnl_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ClearMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 14)); // NOI18N
        jLabel12.setText("Clear");

        javax.swing.GroupLayout pnl_ClearLayout = new javax.swing.GroupLayout(pnl_Clear);
        pnl_Clear.setLayout(pnl_ClearLayout);
        pnl_ClearLayout.setHorizontalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClearLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnl_ClearLayout.setVerticalGroup(
            pnl_ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(pnl_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(pnl_Print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(pnl_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ItemId, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txt_ItemName)
                            .addComponent(txt_SerialNo)
                            .addComponent(txt_UPrice)
                            .addComponent(txt_TPrice)
                            .addComponent(txt_Balance)
                            .addComponent(txt_Cash)
                            .addComponent(txt_Payble)
                            .addComponent(txt_Discount)
                            .addComponent(txt_NoItem, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_UPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Payble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_Sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 3));

        txt_Bill.setColumns(20);
        txt_Bill.setRows(5);
        jScrollPane1.setViewportView(txt_Bill);

        lblSid.setText("SID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblSid, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UPriceActionPerformed

    }//GEN-LAST:event_txt_UPriceActionPerformed

    private void txt_ItemIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ItemIdKeyReleased
        if (txt_ItemId.getText().length() > 0) {
            itemLord();
        }

    }//GEN-LAST:event_txt_ItemIdKeyReleased

    private void txt_ItemIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ItemIdKeyTyped

    }//GEN-LAST:event_txt_ItemIdKeyTyped

    private void txt_NoItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NoItemKeyReleased
       
  
        double price = Double.parseDouble(txt_UPrice.getText());
        double unit = Double.parseDouble(txt_NoItem.getText());
        double tprice = price * unit;
        txt_TPrice.setText(tprice + "");
    }//GEN-LAST:event_txt_NoItemKeyReleased

    private void txt_TPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TPriceActionPerformed

    }//GEN-LAST:event_txt_TPriceActionPerformed

    private void txt_DiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiscountKeyReleased
       //calculate prices
        double discount = Double.parseDouble(txt_Discount.getText());
        double tprice = Double.parseDouble(txt_TPrice.getText());
        double payble = tprice - discount;
        txt_Payble.setText(payble + "");
    }//GEN-LAST:event_txt_DiscountKeyReleased

    private void txt_CashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CashKeyReleased
          //calculate prices
        double cash = Double.parseDouble(txt_Cash.getText());
        double payble = Double.parseDouble(txt_Payble.getText());
        double balance = cash - payble;
        txt_Balance.setText(balance + "");

    }//GEN-LAST:event_txt_CashKeyReleased

    private void pnl_SalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_SalesMouseClicked
        
        makeBill();
        lordData();
        itemLord();
   
        //insert datas on database
        try {
            String q = "INSERT INTO  `sale` (\n"
                    + "  `sale_id` ,\n"
                    + "  `item_id` ,\n"
                    + "  `unit_price` ,\n"
                    + "  `no_of_item` ,\n"
                    + "  `total_price` ,\n"
                    + "  `discount` ,\n"
                    + "  `payable` ,\n"
                    + "  `cash`,\n"
                    + "  `balance`, \n"
                    + "  `date` ) VALUES (?,?,?,?,?,?,?,?,?,?)";

            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setString(1, sid);
            pst.setString(2, iid);
            pst.setString(3, uprice);
            pst.setString(4, noofitem);
            pst.setString(5, totalprice);
            pst.setString(6, discount);
            pst.setString(7, payble);
            pst.setString(8, cash);
            pst.setString(9, balance);
            pst.setString(10, date);
            pst.execute();
            lordData();

        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_pnl_SalesMouseClicked



    private void pnl_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_PrintMouseClicked
        //print the bill
        try {
            txt_Bill.print();
        } catch (Exception printerException) {
        }


    }//GEN-LAST:event_pnl_PrintMouseClicked

    private void pnl_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ClearMouseClicked
        //clear components
        autoId();
        txt_ItemId.setText("");
        txt_ItemName.setText("");
        txt_SerialNo.setText("");
        txt_UPrice.setText("");
        txt_NoItem.setText("");
        txt_TPrice.setText("");
        txt_Discount.setText("");
        txt_Payble.setText("");
        txt_Cash.setText("");
        txt_Balance.setText("");

    }//GEN-LAST:event_pnl_ClearMouseClicked

    //to prepare a bill, use set text
    private void makeBill() {
        txt_Bill.setText(txt_Bill.getText() + "Item Name \t" + txt_ItemName.getText() + "\nNo Of Item\t" + txt_NoItem.getText() + "\nUnit Price\t" + txt_UPrice.getText() + "\nTotal Price\t" + txt_TPrice.getText() + "\n----------------------\nDiscount\t" + txt_Discount.getText() + "\nPayble\t" + txt_Payble.getText() + "\nCash\t" + txt_Cash.getText() + "\n----------------------\nBalance\t" + txt_Balance.getText() + "\n\nThanks for your visit\n");
    }

    //bill header again set text
    private void billHeader() {
        txt_Bill.setText("theM Software\nmelkecelioglu@gmail.com\n\n");
    }
    
    //prepare auto ID's for the next one
    private void autoId() {
        try {
            String sql = "SELECT 'sale_id' FROM sale ORDER BY sale_id DESC LIMIT 1";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("sale_id");
                int co = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                lblSid.setText(ftxt);
            } else {
                lblSid.setText("SID1000");
            }

        } catch (Exception ex) {
          //  JOptionPane.showMessageDialog(rootPane, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSid;
    private javax.swing.JPanel pnl_Clear;
    private javax.swing.JPanel pnl_Print;
    private javax.swing.JPanel pnl_Sales;
    private javax.swing.JTextField txt_Balance;
    private javax.swing.JTextArea txt_Bill;
    private javax.swing.JTextField txt_Cash;
    private javax.swing.JTextField txt_Discount;
    private javax.swing.JTextField txt_ItemId;
    private javax.swing.JTextField txt_ItemName;
    private javax.swing.JTextField txt_NoItem;
    private javax.swing.JTextField txt_Payble;
    private javax.swing.JTextField txt_SerialNo;
    private javax.swing.JTextField txt_TPrice;
    private javax.swing.JTextField txt_UPrice;
    // End of variables declaration//GEN-END:variables
}
