/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import keeptoo.Drag;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author melikekecelioglu
 */
public class SendCode1 extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    int randomCode;

    public SendCode1() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_Email = new javax.swing.JTextField();
        txt_VerifyCode = new javax.swing.JPasswordField();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Verify = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        btn_SendCode1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(40);
        kGradientPanel1.setkEndColor(new java.awt.Color(70, 90, 117));
        kGradientPanel1.setkGradientFocus(350);
        kGradientPanel1.setkStartColor(new java.awt.Color(145, 186, 215));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Email.setBackground(new Color(0,0,0,0));
        txt_Email.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Email.setToolTipText("");
        txt_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 290, 30));

        txt_VerifyCode.setBackground(new Color(0,0,0,0));
        txt_VerifyCode.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_VerifyCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_VerifyCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 290, -1));

        btn_exit.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("   X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 50, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setText("Verify code");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btn_Verify.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0)));
        btn_Verify.setForeground(new java.awt.Color(0, 0, 0));
        btn_Verify.setText("Verify");
        btn_Verify.setToolTipText("");
        btn_Verify.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_Verify.setkBackGroundColor(new Color(0,0,0,0));
        btn_Verify.setkBorderRadius(40);
        btn_Verify.setkEndColor(new java.awt.Color(153, 204, 255));
        btn_Verify.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        btn_Verify.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Verify.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btn_Verify.setkIndicatorThickness(5);
        btn_Verify.setkPressedColor(new Color(0,0,0,0));
        btn_Verify.setkSelectedColor(new Color(0,0,0,0));
        btn_Verify.setkStartColor(new Color(0,0,0,0));
        btn_Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerifyActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_Verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, -1));

        btn_SendCode1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0)));
        btn_SendCode1.setForeground(new java.awt.Color(0, 0, 0));
        btn_SendCode1.setText("Send Code");
        btn_SendCode1.setToolTipText("");
        btn_SendCode1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_SendCode1.setkBackGroundColor(new Color(0,0,0,0));
        btn_SendCode1.setkBorderRadius(40);
        btn_SendCode1.setkEndColor(new java.awt.Color(153, 204, 255));
        btn_SendCode1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        btn_SendCode1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_SendCode1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btn_SendCode1.setkIndicatorThickness(5);
        btn_SendCode1.setkPressedColor(new Color(0,0,0,0));
        btn_SendCode1.setkSelectedColor(new Color(0,0,0,0));
        btn_SendCode1.setkStartColor(new Color(0,0,0,0));
        btn_SendCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendCode1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_SendCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed

    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged

        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed

        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerifyActionPerformed
        //check the verify code == randomcode
        if (Integer.valueOf(txt_VerifyCode.getText()) == randomCode) {
            Reset1 rs = new Reset1(txt_Email.getText());
            rs.setVisible(true);
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "code do not match");
        }


    }//GEN-LAST:event_btn_VerifyActionPerformed

    private void btn_SendCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendCode1ActionPerformed

        //send code
        try {
            //create a random number from 0-999999
            Random rand = new Random();
            randomCode = rand.nextInt(999999);
            //specify host, user, pass, to, subject
            String host = "smtp.gmail.com";
            String user = "melkecelioglu@gmail.com";
            String pass = "9marley370";
            String to = txt_Email.getText();
            String subject = "Reseting code";
            boolean sessionDebug = false;
            //mail message is created 
            String msg = "YOUR RESET CODE IS: " + randomCode;
            
            //to maintain lists of values in which the key is a String
            //and the value is also a String, use Properties.
            Properties props = new Properties();
            props.setProperty("mail.transport.protocol", "smtp");
            props.setProperty("mail.host", "smtp.gmail.com");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.port", "465");
            props.put("mail.debug", "true");
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            props.put("mail.smtp.socketFactory.fallback", "false");
            
            //mail authenticator
            Session session = Session.getDefaultInstance(props,
                    new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication("melkecelioglu@gmail.com", "9marley370");
                }
            });

            //transport the mail
            Transport transport = session.getTransport();
            InternetAddress addressFrom = new InternetAddress("melkecelioglu@gmail.com");

            MimeMessage messag = new MimeMessage(session);
            messag.setSender(addressFrom);
            messag.setSubject(subject);
            messag.setContent(msg, "text/plain");
            messag.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            transport.connect();
            Transport.send(messag);
            transport.close();
            JOptionPane.showMessageDialog(null, "code has been send to the email");

        } catch (MessagingException ex) {

            JOptionPane.showMessageDialog(rootPane, ex);
        }


    }//GEN-LAST:event_btn_SendCode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendCode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendCode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendCode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendCode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendCode1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_SendCode1;
    private keeptoo.KButton btn_Verify;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JPasswordField txt_VerifyCode;
    // End of variables declaration//GEN-END:variables
}
