/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import keeptoo.Drag;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author melikekecelioglu
 */
public class SignUp1 extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;

    int x, y;

    public SignUp1() {
        initComponents();
        this.setLocationRelativeTo(this);
        con = DBConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_UserName = new javax.swing.JTextField();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kbtn_Register = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_RePassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(40);
        kGradientPanel1.setkEndColor(new java.awt.Color(70, 90, 117));
        kGradientPanel1.setkGradientFocus(350);
        kGradientPanel1.setkStartColor(new java.awt.Color(133, 156, 157));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_UserName.setBackground(new Color(0,0,0,0));
        txt_UserName.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_UserName.setForeground(new java.awt.Color(255, 255, 255));
        txt_UserName.setToolTipText("");
        txt_UserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 380, 30));

        btn_exit.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("   X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 50, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        kbtn_Register.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0)));
        kbtn_Register.setForeground(new java.awt.Color(0, 0, 0));
        kbtn_Register.setText("Register");
        kbtn_Register.setToolTipText("");
        kbtn_Register.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        kbtn_Register.setkBackGroundColor(new Color(0,0,0,0));
        kbtn_Register.setkBorderRadius(40);
        kbtn_Register.setkEndColor(new java.awt.Color(204, 204, 255));
        kbtn_Register.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kbtn_Register.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtn_Register.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kbtn_Register.setkIndicatorThickness(5);
        kbtn_Register.setkPressedColor(new Color(0,0,0,0));
        kbtn_Register.setkSelectedColor(new Color(0,0,0,0));
        kbtn_Register.setkStartColor(new Color(0,0,0,0));
        kbtn_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kbtn_RegisterMouseClicked(evt);
            }
        });
        kbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn_RegisterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kbtn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 120, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txt_Email.setBackground(new Color(0,0,0,0));
        txt_Email.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));
        txt_Email.setToolTipText("");
        txt_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 380, 30));

        txt_Password.setBackground(new Color(0,0,0,0));
        txt_Password.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        txt_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 380, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txt_RePassword.setBackground(new Color(0,0,0,0));
        txt_RePassword.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_RePassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_RePassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_RePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 380, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Re-Password");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");
        jLabel1.setToolTipText("");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 80));

        txt_ID.setBackground(new Color(0,0,0,0));
        txt_ID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_ID.setToolTipText("");
        txt_ID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 380, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed


    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void kbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn_RegisterActionPerformed

        //control datas, insert datas to database if all acceptable,
        String id = txt_ID.getText();
        String uname = txt_UserName.getText();
        String email = txt_Email.getText();
        String pword = txt_Password.getText();
        String rpword = txt_RePassword.getText();
        if ((id.equals("") || uname.equals("") || email.equals("") || pword.equals("") || rpword.equals("")) || (!pword.equals(rpword))) {
            JOptionPane.showMessageDialog(this, "Please enter all datas or check the matching of password and re-password");

        } else {

            JOptionPane.showMessageDialog(this, "Successfuly Signed Up!");

            try {
                String q = "INSERT INTO  `register` (\n"
                        + "  `id` ,\n"
                        + "  `user_name` ,\n"
                        + "  `email` ,\n"
                        + "  `password` ,\n"
                        + "  `re_password`) VALUES (?,?,?,?,?)";

                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, id);
                pst.setString(2, uname);
                pst.setString(3, email);
                pst.setString(4, pword);
                pst.setString(5, rpword);
                pst.execute();

                LogIn_1 lo = new LogIn_1();
                lo.setVisible(true);

            } catch (Exception ex) {

            }

        }
    }//GEN-LAST:event_kbtn_RegisterActionPerformed

    private void kbtn_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kbtn_RegisterMouseClicked

    }//GEN-LAST:event_kbtn_RegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton kbtn_Register;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JPasswordField txt_RePassword;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
